### ISSUE TITLE
URL seems to be empty?

### ISSUE THREAD

**Issue by FilippoULIVO** [Sheemon7/etf_filter#2]
Hey i was trying to refactor your code in a jupiter notebook on something that looks more or less like this

```
import pandas as pd
import requests
from bs4 import BeautifulSoup

url='https://www.justetf.com/uk/etf-profile.html?isin={0}'

req =requests.get(url) #proxies={'http':"90.45.28.27"}
cont=req.content

response=BeautifulSoup(cont,"html.parser")

all= response.find_all()
all

#1 
for fin in all:
    etf = {}
    try:
       print(response.find('span', attrs={'class': 'h1'}
            ).text.strip())
    except AttributeError :
        print("Fund isin '{}' not found!") 
    
```
I did the print to figure if anything would have been added to the etf dictionary before implementing your method
Unfortunately my output always hits the nonetype exception  and returns around 1327 of

```
Fund isin '{}' not found!
```

the number of exceptions makes me think i'm hitting the right spot  but i can't figure what i'm doing wrong
I'm sorry if this seems pretentious and maybe it's a silly mistake(i'm a junior after all) but i was wondering if you could help me out ;
i was trying to collect the 5 year volatility

**Comment by simonmandlik** [comment]
Hi, you need to provide ISIN of the etf you're interested in. E.g., this works:

```python
import pandas as pd
import requests
from bs4 import BeautifulSoup

url='https://www.justetf.com/uk/etf-profile.html?isin={}'

isin = 'LU1602144906'
req =requests.get(url.format(isin))
cont=req.content
response=BeautifulSoup(cont,"html.parser")

all= response.find_all()
 
for fin in all:
    etf = {}
    try:
       print(response.find('span', attrs={'class': 'h1'}
            ).text.strip())
    except AttributeError :
        print("Fund isin '{}' not found!") 
```
